### ISSUE TITLE
"Edit in Zed" icon is not opening Zed window

### ISSUE THREAD

**Issue by kpitt** [zedapp/edit-in-zed#4]
Clicking on the "Edit in Zed" icon in a textarea is no longer opening the Zed editor window. This used to work when I first installed the extension a month or so ago.

In the Developer Tools Console it shows "Connecting Chrome app to edit" (or "Connecting Chrome app to edit textarea contents" if the textarea already contains text), but nothing else happens. I tried starting Zed from the Chrome App Launcher first before clicking the icon, and I also tried completely removing and reinstalling both the Zed application and the Edit in Zed extension, but neither helped.

I tested on both Mac OSX 10.8 and Windows 8.1 with the same results. Both OS's are running the latest Chrome update 37.0.2062.120.

**Comment by zefhemel** [comment]
Are you running Zed from the chrome app store or running the latest master from Github?

**Comment by kpitt** [comment]
I installed both the app and the extension from the App Store. The Zed version shown in the project picker is 0.13.0.

**Comment by zefhemel** [comment]
Is the zed project picker window open as you try this?— Zef

**Comment by zefhemel** [comment]
Anyway, this has been reworked quite heavily for 1.0 (current master), there it doesn't require having the project picker open.

**Comment by kpitt** [comment]
Oops, I composed a reply a few days ago but apparently forgot to submit it.

I first tried without opening Zed first. I thought that's how I had done it previously when it was working. When that didn't do anything, I tried opening Zed first and clicking the Edit in Zed icon while the project picker was open but it still didn't work. I just retested to be sure, both by opening Zed from the Chrome App Launcher in the Windows task bar and also by opening Zed from this same Chrome instance.

If I want to try the current master, do I need to install just the edit-in-zed extension from the GitHub repo, or install the latest zed editor app from GitHub as well?

**Comment by zefhemel** [comment]
Yeah I think you have to install both manually, unfortunately. However, the 1.0 release (current master) is planned within two weeks so you can also wait a little bit.

**Comment by kpitt** [comment]
Sounds good. I'll update the issue status after the new release comes out.

**Comment by kpitt** [comment]
Seems to be working again with Zed 1.0. Thanks for the update!

**Comment by zefhemel** [comment]
Great!— Zef
